### DISCUSSION TITLE
Fail to set up rabbitmq-exporter

### DISCUSSION THREAD

**Discussion by BigBoulard** [kbudde/rabbitmq_exporter#351] [Q&A]
Hi guys,

I'm working with `docker-desktop` on a Mac. I've spent hours trying to set up `rabbitmq-exporter` to expose the metrics for Prometheus. I probably missed something obvious cause I often struggle with networking and system stuff.

Prometheus seems to work well cause I succeeded in making it work with `postgres` and  `bitnami/postgres-exporter`. In `Status > Targets`, I can see the `postgres exporter` is up but `rabbitmq-exporter` stays down with the below error:

```sh
Get "http://localhost:15692/metrics?format=prometheus": dial tcp 127.0.0.1:15692: connect: connection refused
```

I've created a `metrics_user` user through the `Rabbitmq management` interface on `http://localhost:15672/#/users`. I added the `monitoring` tag, and I naively added permissions on virtual host `/` with the regexp `.*` for `configure`, `write` and `read`, and added `.*` on `read` and `write` on all `exchanges`.

I noticed that for whatever reason, `Rabbitmq` can only be accessed through `localhost` whereas `Postgres` can be accessed by the container name like `project-postgres-1`... don't know if it has something to do with the `RABBITMQ_DEFAULT_VHOST` or `RABBITMQ_NODENAME` env vars... 

Below is the associated part of my `docker-compose` file:

Thank you so much :)

```yaml
 services:

  # see https://www.rabbitmq.com/configure.html#supported-environment-variables
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - rabbitmq-vol:/var/lib/rabbitmq/
    networks:
      - rabbitmq-net
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      # - RABBITMQ_DEFAULT_VHOST=project-rabbitmq-1 # only meant to be used in development and CI environments
      # - RABBITMQ_NODENAME=rabbit1@project-rabbitmq-1 # unique per Erlang-node-and-machine combination

  # see https://github.com/kbudde/rabbitmq_exporter#settings
  rabbitmq-exporter:
    image: kbudde/rabbitmq-exporter:latest
    ports:
      - 15692:15692
    environment:
      - RABBIT_URL=http://localhost:15672/metrics # <------------ RabbitMQ Management URL
      - RABBIT_USER=metrics_user # <----------- freshly created rabbitmq user
      - RABBIT_PASSWORD=password
      - RABBIT_CONNECTION=direct
      - LOG_LEVEL=debug # <---------------- trying to get more info ...
    networks:
      - rabbitmq-net
    depends_on:
      - rabbitmq

  # see https://hub.docker.com/r/prom/prometheus
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus:/etc/prometheus # bind mount config
      - prometheus-vol:/prometheus # named volume to save the data
    networks:
      - postgres-net
      - rabbitmq-net
      - prometheus-net
    depends_on:
      - postgres-exporter
      - rabbitmq-exporter
```

Here are the exporter logs:

```sh
time="2023-09-08T06:45:16Z" level=info msg="Using default certificate pool"
time="2023-09-08T06:45:16Z" level=info msg="Starting RabbitMQ exporter" BRANCH=HEAD BUILD_DATE="2022-07-21T19:02:55Z" REVISION=40d9c32 VERSION=1.0.0-RC19
time="2023-09-08T06:45:16Z" level=info msg="Active Configuration" CAFILE=ca.pem CERTFILE=client-cert.pem EXCLUDE_METRICS="[]" INCLUDE_EXCHANGES=".*" INCLUDE_QUEUES=".*" INCLUDE_VHOST=".*" KEYFILE=client-key.pem MAX_QUEUES=0 OUTPUT_FORMAT=TTY PUBLISH_ADDR= PUBLISH_PORT=9419 RABBIT_CAPABILITIES="no_sort,bert" RABBIT_CONNECTION=direct RABBIT_EXPORTERS="[exchange node overview queue]" RABBIT_TIMEOUT=30 RABBIT_URL="http://localhost:15672/metrics" RABBIT_USER=metrics_user SKIPVERIFY=false SKIP_EXCHANGES="^$" SKIP_QUEUES="^$" SKIP_VHOST="^$"
```
