### ISSUE TITLE
Docker Compose

### ISSUE THREAD

**Issue by juliofalbo** [kbudde/rabbitmq_exporter#157]
Hi.
I would like to create a docker-compose with both commands:
` docker run -d -e RABBITMQ_NODENAME=my-rabbit --name my-rabbit -p 9419:9419 rabbitmq:3-management`

` docker run -d --net=container:my-rabbit kbudde/rabbitmq-exporter`

But instead of using this port 9419, I would like to use the default port (**5672**).

I tried the config below but it is not working.

```
version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: "rabbitmq"
    environment:
      - RABBITMQ_NODENAME:rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
      - "9419:9419"
  rabbitmq-exporter:
    image: kbudde/rabbitmq-exporter
    container_name: "rabbitmq-exporter"
    depends_on:
      - rabbitmq
```

Thank you.

**Comment by zerkms** [comment]
You should specify that port on the `rabbitmq-exporter` service.

**Comment by kbudde** [comment]
Hi,

the compose configuration for both commands is:

```
version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: "rabbitmq"
    environment:
      - RABBITMQ_NODENAME:rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
      - "9419:9419"
  rabbitmq-exporter:
    image: kbudde/rabbitmq-exporter
    container_name: "rabbitmq-exporter"
    network_mode: container:rabbitmq
```

- port 15672 is the rabbitmq management plugin. 
- port 5672 is the amqp port where your applications can connect to rabbitmq
- port 9419 is the port of the exporter where the metrics are exposed. This ports needs only to be accessed by prometheus.

I'm using special network mode container, because it is easier. Both containers are sharing the same ip. The exporter can access rabbitmq with loopback 127.0.0.1 address and default credentials (guest/guest).
The guest user should be disabled by default for remote access (it's an admin with known password).

Other solution would be to not share the same network. 
```
version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: "rabbitmq"
    environment:
      - RABBITMQ_NODENAME:rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
  rabbitmq-exporter:
    image: kbudde/rabbitmq-exporter
    container_name: "rabbitmq-exporter"
    ports:
        - "9419:9419" # exposed on container providing the port
    environment: 
      - RABBIT_URL=http://rabbitmq:15672
      #- RABBIT_USER=exporter
      #- RABBIT_PASSWORD=PASSWORD_FOR_USER_EXPORTER_WITH_MONITORING_PERMISSION
```
