### ISSUE TITLE
Queue replication status is not output

### ISSUE THREAD

**Issue by SEbbaDK** [kbudde/rabbitmq_exporter#307]
It seems like the `queue_slave_nodes_len` (and the sync'ed variety) introduced in #159 is not exported.

I have created a small docker stack setup to showcase the problem:

```yaml
version: "3.9"

services:
    rabbitmq-1:
        image: rabbitmq:3.10.10
        networks:
            mq-net:
        environment:
            RABBITMQ_DEFAULT_USER: mq
            RABBITMQ_DEFAULT_PASS: mq
            RABBITMQ_ERLANG_COOKIE: "mymq"

    rabbitmq-2:
        image: rabbitmq:3.10.10
        networks:
            mq-net:
        environment:
            RABBITMQ_DEFAULT_USER: mq
            RABBITMQ_DEFAULT_PASS: mq
            RABBITMQ_ERLANG_COOKIE: "mymq"

    exporter:
        image: kbudde/rabbitmq-exporter:1.0.0-RC19
        networks:
            mq-net:
        environment:
            RABBIT_URL: "http://rabbitmq-1:15672"
            RABBIT_USER: mq
            RABBIT_PASSWORD: mq
            RABBIT_EXPORTERS: "connections,shovel,federation,exchange,node,queue,memory"

networks:
    mq-net:
```

I cluster the two instances with the CLI and create a quorum queue. But running `curl exporter:9419/metrics` does not output the two metrics but outputs nearly everything else.
