### ISSUE TITLE
Using per-queue exporter with the official one

### ISSUE THREAD

**Issue by Dmytro-Shvetsov** [kbudde/rabbitmq_exporter#371]
Hey there,

I've configured prometheus to scrape both detailed and standard rabbitmq metrics, so that both of these dashboards are working
- https://grafana.com/grafana/dashboards/4279-rabbitmq-monitoring/
- https://grafana.com/grafana/dashboards/17308-rabbitmq-queue/

However, whenever I configure both detailed and default exporters in the prometheus config, they don't seem to integrate well. Either of the dashboards just doesn't successfully execute the queries, and I assume the problem is in the `rabbitmq_queue_info` suggested to be added in this [blogpost](https://hodovi.cc/blog/rabbitmq-per-queue-monitoring/).
```
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'rabbitmq'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['rabbitmq:15692']

  - job_name: 'rabbitmq-detailed'
    metrics_path: /metrics/detailed
    params:
      family: 
        - queue_coarse_metrics
        - queue_consumer_count
    scheme: http
    static_configs:
      - targets: ['rabbitmq:15692']

  - job_name: 'rabbitmq-queue-monitoring'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['rabbitmq-exporter:9419']
```

Prometheus rules config:
```
groups:
  - name: rabbitmq.rules
    rules:
    - expr: rabbitmq_detailed_queue_consumers * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) max(rabbitmq_identity_info) by (rabbitmq_cluster, instance, rabbitmq_node)
      record: rabbitmq_queue_info

```

It seems since both `rabbitmq` and `rabbitmq-detailed` jobs use the same metrics scrapping target, they are registered as two different replicas of rabbitmq queues, so the queries are messed up. 

Thank you in advance for any guidance!

BR,

Dmytro
