### ISSUE TITLE
cant make RABBIT_CAPABILITIES work

### ISSUE THREAD

**Issue by Anmorata** [kbudde/rabbitmq_exporter#43]
I'm running exporter on kubernetes. everything work fine exept RABBIT_CAPABILITIES.

```
        env:
        - name: RABBIT_USER
          value: user
        - name: RABBIT_PASSWORD
          value: password
        - name: INCLUDE_QUEUES
          value: ".*"
        - name: RABBIT_CAPABILITIES
          value: "vhost"
```

its my config file. 
and its log in kubernetes:

`time="2017-09-06T20:05:16Z" level=info msg="Starting RabbitMQ exporter" BRANCH=master BUILD_DATE="20170904-20:48:49" OUTPUT_FORMAT=TTY PUBLISH_PORT=9090 RABBIT_CAPABILITIES= RABBIT_URL="http://localhost:15672" RABBIT_USER=user REVISION=532c8d61263b1f2f66a74221be4815d5509ca827 VERSION=0.20.0 `

rabbit version: RabbitMQ 3.6.11 on Erlang 19.2.1
