### ISSUE TITLE
not able to see the data in prometheus after adding exporter

### ISSUE THREAD

**Issue by abhijt-zanak** [kbudde/rabbitmq_exporter#63]
I have done the setup of rabbitmq and exporter, however nota ble to see the rabbitmq data in prometheus, I can see the data in rabbitmq exporter.

deployment.yaml
```
`apiVersion: apps/v1beta1
kind: Deployment
metadata:
 name: rezoomex-rabbitmq-deployment
 labels:
  app: queue
spec:
 replicas: 1
 template:
  metadata:
   labels:
    app: rabbitmq
  spec:
   containers:
    - name: rabbitmq
      image: rabbitmq:3.6.11-management-alpine
      env:
        - name: RABBITMQ_DEFAULT_USER
          value: user
        - name: RABBITMQ_DEFAULT_PASS
          value: password
      ports:
        - name: rabbitmq
          containerPort: 5672
          protocol: TCP
        - name: rabbitmq1
          containerPort: 15672
          protocol: TCP
    - name: rabbitmq-exporter  
      image: kbudde/rabbitmq-exporter
      ports:
        - name: exporter 
          containerPort: 9090
      env:
        - name: RABBIT_USER
          value: user
        - name: RABBIT_PASSWORD
          value: password`
```
-----
Service.yaml
```
`apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: default
  labels:
    app: rabbitmq-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"  
spec:
  type: LoadBalancer
  ports:
  - name: rabbitmq
    port: 5672
    #targetPort: 15672
    protocol: TCP
  - name: rabbitmq1
    port: 15672
    protocol: TCP
  - name: exporter
    port: 9090
    targetPort: exporter
    protocol: TCP
  selector:
    app: rabbitmq`
```

when I logged into promethuus and serached for 'rabbitmq_queuesTotal' it showed me no data
<img width="855" alt="exporter-data" src="https://user-images.githubusercontent.com/6571813/33517512-c7482bd0-d7ab-11e7-91b5-4b8c53926b2c.png">
<img width="907" alt="prometheus" src="https://user-images.githubusercontent.com/6571813/33517513-c77082e2-d7ab-11e7-954f-3f5726b80c49.png">
